### PR TITLE
fixing jec uncertainty loading

### PR DESCRIPTION
**Pull request by dsrankin**

### CODE REVIEW

**Comment by jmhogan** [comment]
I think this change was a mistake -- it's causing me seg faults when doing
the JEC shifts.

GOT UNCERTAINTY FILE:
/uscms_data/d3/jmanagan/LJMetSubmit7414/src/LJMet/Com/data/Summer15_25nsV5_DATA_UncertaintySources_AK4PFchs.txt
%MSG-e JetCorrectorParameters:
No definitions found!!!
%MSG
%MSG-e JetCorrectorParameters:
the requested section  doesn't exist!
%MSG

[ljmet]: 0 events processed. Processing run 1, event 99299201
trying to set vars in jecUnc
SET pt and eta in jecUnc
trying to get uncertainty

 **\* Break **\* segmentation violation

I reverted this change and it runs successfully.

Julie

On Tue, Oct 27, 2015 at 11:38 AM, drankincms notifications@github.com
wrote:

> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/cms-ljmet/Ljmet-Com/pull/79
> Commit Summary
> - fixing jec uncertainty loading
> 
> File Changes
> - _M_ src/BaseEventSelector.cc
>   https://github.com/cms-ljmet/Ljmet-Com/pull/79/files#diff-0 (2)
> 
> Patch Links:
> - https://github.com/cms-ljmet/Ljmet-Com/pull/79.patch
> - https://github.com/cms-ljmet/Ljmet-Com/pull/79.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/79.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by dsrankin** [comment]
Julie,

Hmm, thats very strange, I get seg faults if I don't make this change...

If it works for you the old way, I would say you should make the change
locally and then after Friday we can try to sort out what is going on here.

-Dylan

**Comment by jmhogan** [comment]
Sounds good!

Julie

On Wed, Oct 28, 2015 at 11:23 AM, drankincms notifications@github.com
wrote:

> Julie,
> 
> Hmm, thats very strange, I get seg faults if I don't make this change...
> 
> If it works for you the old way, I would say you should make the change
> locally and then after Friday we can try to sort out what is going on here.
> 
> -Dylan
> 
> On Wed, Oct 28, 2015 at 4:24 PM, jmhogan notifications@github.com wrote:
> 
> > I think this change was a mistake -- it's causing me seg faults when
> > doing
> > the JEC shifts.
> > 
> > GOT UNCERTAINTY FILE:
> > 
> > /uscms_data/d3/jmanagan/LJMetSubmit7414/src/LJMet/Com/data/Summer15_25nsV5_DATA_UncertaintySources_AK4PFchs.txt
> > %MSG-e JetCorrectorParameters:
> > No definitions found!!!
> > %MSG
> > %MSG-e JetCorrectorParameters:
> > the requested section doesn't exist!
> > %MSG
> > 
> > [ljmet]: 0 events processed. Processing run 1, event 99299201
> > trying to set vars in jecUnc
> > SET pt and eta in jecUnc
> > trying to get uncertainty
> > 
> > **\* Break **\* segmentation violation
> > 
> > I reverted this change and it runs successfully.
> > 
> > Julie
> > 
> > On Tue, Oct 27, 2015 at 11:38 AM, drankincms notifications@github.com
> > wrote:
> > 
> > > ---
> > > 
> > > You can view, comment on, or merge this pull request online at:
> > > 
> > > https://github.com/cms-ljmet/Ljmet-Com/pull/79
> > > Commit Summary
> > > - fixing jec uncertainty loading
> > > 
> > > File Changes
> > > - _M_ src/BaseEventSelector.cc
> > >   https://github.com/cms-ljmet/Ljmet-Com/pull/79/files#diff-0 (2)
> > > 
> > > Patch Links:
> > > - https://github.com/cms-ljmet/Ljmet-Com/pull/79.patch
> > > - https://github.com/cms-ljmet/Ljmet-Com/pull/79.diff
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/cms-ljmet/Ljmet-Com/pull/79.
> > 
> > ## 
> > 
> > _Julie M. Hogan_
> > Brown University
> > Dept. of Physics
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cms-ljmet/Ljmet-Com/pull/79#issuecomment-151880318.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/79#issuecomment-151899354.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by clint-richardson** [comment]
Hi All,

It works for me with Dylan's PR. Julie I noticed something in your error message that maybe is part of it. You are using the Uncertainty**Sources** file as opposed to the one with just Uncertainty in the name. Dylan and I were just looking at this question and we think we are supposed to use the one with just Uncertainty. Is it possible that the seg fault is because the 'Sources' files don't have what we actually need in them? This would then also mean that perhaps in the old setup the file wasn't being read in or something. I don't know just a thought, but maybe try Dylan's PR with just the uncertainties file?

**Comment by jmhogan** [comment]
Ok, it looks like this is a case of JEC redundency!

I get identical AK4 Jet pT distributions from "JECup" with these two
combinations (and in both, JECup is different from the nominal):
1. "UncertaintySources" + old BES
2. "Uncertainty" + new BES.

The new way is certainly simpler to understand, but has to go along with
the file name change in the config. So we should push changes to the
example configs as well.

Julie

On Thu, Oct 29, 2015 at 4:55 AM, Clint Richardson notifications@github.com
wrote:

> Hi All,
> 
> It works for me with Dylan's PR. Julie I noticed something in your error
> message that maybe is part of it. You are using the Uncertainty_Sources_
> file as opposed to the one with just Uncertainty in the name. Dylan and I
> were just looking at this question and we think we are supposed to use the
> one with just Uncertainty. Is it possible that the seg fault is because the
> 'Sources' files don't have what we actually need in them? This would then
> also mean that perhaps in the old setup the file wasn't being read in or
> something. I don't know just a thought, but maybe try Dylan's PR with just
> the uncertainties file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/79#issuecomment-152131828.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by clint-richardson** [comment]
Hi Julie,

Thanks for doing that check! Yes this was a subtle error since we all had
working recipes but also both encountered failures :)

Best,
-Clint

**Pull request merged**
