### PR TITLE
adjusting dr match for JER in case of AK8 jets (0.2 for AK4, 0.4 for AK8)

### PR DESCRIPTION
**Pull request by dsrankin**

### CODE REVIEW

**Comment by dsrankin** [comment]
I don't actually use AK8 jets, so I will wait to actually merge this until someone who cares comments. This dR is the suggestion from here: https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#Smearing_procedures.

**Comment by dsrankin** [comment]
Ok I lied, since I have a new commit that goes on top of this and I want to avoid trying to separate the two merges. In any case, this is a very basic commit and should be very easy to undo in case someone has a real issue with it.

**Comment by jmhogan** [comment]
Nope, you're exactly right, they say cone-size/2. Thanks :)

On Wed, Apr 20, 2016 at 10:51 AM, drankincms notifications@github.com
wrote:

> Merged #113 https://github.com/cms-ljmet/Ljmet-Com/pull/113.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/113#event-634760847

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by dsrankin** [comment]
Didn't mean to combine these commits necessarily...

I have added the random smearing method in case the scaling method fails. The random number generator seed is the jet phi value, and I have checked that the same jet always gets the same smeared pt across all functions. The scaling method succeeds almost every time, so this is a very minor change.

**Comment by jmhogan** [comment]
Dylan,

I had "factor" set up like it was previously -- subtracting 1 from the SF.
So does anything pass (!smeared && factor > 1)?

Julie

On Wed, Apr 20, 2016 at 10:57 AM, drankincms notifications@github.com
wrote:

> Didn't mean to combine these commits necessarily...
> 
> I have added the random smearing method in case the scaling method fails.
> The random number generator seed is the jet phi value, and I have checked
> that the same jet always gets the same smeared pt across all functions. The
> scaling method succeeds almost every time, so this is a very minor change.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/113#issuecomment-212489112

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by dsrankin** [comment]
Good catch, just fixed this.

**Pull request merged**
