### PR TITLE
adding option to override LHE weights with LHAPDF, and save specific ID+status combinations

### PR DESCRIPTION
**Pull request by dsrankin**
both of these are specific to singleLep so will need to be ported to dilepton stuff if needed

### CODE REVIEW

**Comment by dsrankin** [comment]
This also involves an update to PileUpCalc which we have all almost certainly made locally which allows it to run on miniAODv2

**Comment by jmhogan** [comment]
Dylan,

What MC can use the LHAPDF stuff? The upcoming 76X? The MiniAODv2?

Julie

On Wed, Dec 16, 2015 at 3:58 AM, drankincms notifications@github.com
wrote:

> Merged #89 https://github.com/cms-ljmet/Ljmet-Com/pull/89.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/89#event-493268632.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by dsrankin** [comment]
Julie,

LHAPDF is independent of the MC release as far as I know, it only needs
some basic parton information from the LHE collection. Getting it to run
successfully requires some proper environment setup, and it is a bit slow,
so unless you really need it (i.e. the PDF LHE weights are not contained in
the files) I would avoid it. If you are interested I can send some
instructions.

-Dylan

**Comment by jmhogan** [comment]
Yes please -- this might be useful for the diboson samples where we don't
have the info.

Thanks,
Julie

On Wed, Dec 16, 2015 at 9:51 AM, drankincms notifications@github.com
wrote:

> Julie,
> 
> LHAPDF is independent of the MC release as far as I know, it only needs
> some basic parton information from the LHE collection. Getting it to run
> successfully requires some proper environment setup, and it is a bit slow,
> so unless you really need it (i.e. the PDF LHE weights are not contained in
> the files) I would avoid it. If you are interested I can send some
> instructions.
> 
> -Dylan
> 
> On Wed, Dec 16, 2015 at 4:40 PM, jmhogan notifications@github.com wrote:
> 
> > Dylan,
> > 
> > What MC can use the LHAPDF stuff? The upcoming 76X? The MiniAODv2?
> > 
> > Julie
> > 
> > On Wed, Dec 16, 2015 at 3:58 AM, drankincms notifications@github.com
> > wrote:
> > 
> > > Merged #89 https://github.com/cms-ljmet/Ljmet-Com/pull/89.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/cms-ljmet/Ljmet-Com/pull/89#event-493268632.
> > 
> > ## 
> > 
> > _Julie M. Hogan_
> > Brown University
> > Dept. of Physics
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cms-ljmet/Ljmet-Com/pull/89#issuecomment-165147761.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/89#issuecomment-165152594.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Comment by dsrankin** [comment]
Julie,

The PR I just merged should give you the information you need, but please
let me know if something is still unclear (or doesn't work).

-Dylan

**Comment by clint-richardson** [comment]
Hi Julie,

Which diboson samples didn't have it? I got pdf weights for WZ and ZZ.

**Comment by jmhogan** [comment]
Our WW, WZ, and ZZ were just Pythia8 samples and didn't have the info --
I'll check against your sample definition, we might need to switch.

Julie

On Wed, Dec 16, 2015 at 11:57 AM, Clint Richardson <notifications@github.com

> wrote:
> 
> Hi Julie,
> 
> Which diboson samples didn't have it? I got pdf weights for WZ and ZZ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-ljmet/Ljmet-Com/pull/89#issuecomment-165190152.

## 

_Julie M. Hogan_
Brown University
Dept. of Physics

**Pull request merged**
