### PR TITLE
Adding JER/JEC inside event selector

### PR DESCRIPTION
**Pull request by clint-richardson**
Hi All,

Here is my thought on how to save the jec/jer uncertainties in one go of ljmet. Basically I defined functions to scale and smear here:

https://github.com/clint-richardson/Ljmet-Com/blob/CMSSW_8_0_X-RunDepJEC/interface/BaseEventSelector.h#L139-L140
https://github.com/clint-richardson/Ljmet-Com/blob/CMSSW_8_0_X-RunDepJEC/src/BaseEventSelector.cc#L474-L543

They rely on the fact that the jet is already cleaned/corrected. Hence I call them like so in DileptonCalc:

https://github.com/clint-richardson/Ljmet-Com/blob/CMSSW_8_0_X-RunDepJEC/src/BaseEventSelector.cc#L474-L543

Let me know what you guys think and hope it's useful!

### CODE REVIEW

**Comment by dsrankin** [comment]
Do the "syst" parameters in the correctJet functions already do this? Or am I misinterpreting things?

https://github.com/drankincms/Ljmet-Com/blob/CMSSW_8_0_X/src/BaseEventSelector.cc#L446

**Comment by clint-richardson** [comment]
Yea I saw those, but didn't remember anyone talking about putting them there so I kinda ignored them in case they had other uses as well. I also thought it would be nice to separate the two functions so we don't have to re-correct every time.

**Comment by dsrankin** [comment]
I put them in a while back for this purpose, and you can use them in singleLep with the doAllJetSyst flag, but I confess that I still run separate ljmet jobs since my post-ljmet setup expects that and I never updated. On the todo list :)

**Comment by clint-richardson** [comment]
Ah ok, good to know

**Pull request merged**
